-- MySQL Script generated by MySQL Workbench
-- Mon Aug 13 15:07:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema avaliacaoinfnet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema avaliacaoinfnet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avaliacaoinfnet` DEFAULT CHARACTER SET utf8 ;
USE `avaliacaoinfnet` ;

-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`aluno` (
  `id` BIGINT(20) NOT NULL,
  `sexo` VARCHAR(20) NULL,
  `nome` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`curso` (
  `id` BIGINT(20) NOT NULL,
  `codigo` VARCHAR(255) NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`bloco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`bloco` (
  `id` BIGINT(20) NOT NULL,
  `nome` VARCHAR(255) NULL,
  `codigo` VARCHAR(255) NULL,
  `id_curso` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bloco_curso1_idx` (`id_curso` ASC),
  CONSTRAINT `fk_bloco_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `avaliacaoinfnet`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`modulo` (
  `id` BIGINT(20) NOT NULL,
  `nome` VARCHAR(255) NULL,
  `codigo` VARCHAR(255) NULL,
  `id_bloco` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modulo_bloco1_idx` (`id_bloco` ASC),
  CONSTRAINT `fk_modulo_bloco1`
    FOREIGN KEY (`id_bloco`)
    REFERENCES `avaliacaoinfnet`.`bloco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`professor` (
  `id` BIGINT(20) NOT NULL,
  `matricula` VARCHAR(255) NULL,
  `nome` VARCHAR(255) NULL,
  `sexo` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`turma` (
  `id` BIGINT(20) NOT NULL,
  `codigo` VARCHAR(255) NULL,
  `inicio` DATETIME NULL,
  `termino` DATETIME NULL,
  `id_modulo` BIGINT(20) NOT NULL,
  `id_professor` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turma_professor1_idx` (`id_professor` ASC),
  CONSTRAINT `fk_turma_modulo1`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `avaliacaoinfnet`.`modulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `avaliacaoinfnet`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`turma_x_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`turma_x_aluno` (
  `id` BIGINT(20) NOT NULL,
  `id_turma` BIGINT(20) NOT NULL,
  `id_aluno` BIGINT(20) NOT NULL,
  INDEX `fk_respondente_turma1_idx` (`id_turma` ASC),
  INDEX `fk_respondente_aluno1_idx` (`id_aluno` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_respondente_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `avaliacaoinfnet`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respondente_aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `avaliacaoinfnet`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`usuario` (
  `id` BIGINT(20) NOT NULL,
  `usuario` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`questionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`questionario` (
  `id` BIGINT(20) NOT NULL,
  `mensagem_email` LONGTEXT NULL,
  `assunto_email` VARCHAR(255) NULL,
  `codigo` VARCHAR(255) NULL,
  `objetivo` LONGTEXT NULL,
  `id_usuario` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questionario_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_questionario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `avaliacaoinfnet`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`avaliacao` (
  `id` BIGINT(20) NOT NULL,
  `data_resposta` DATE NULL,
  `inicio` DATETIME NULL,
  `termino` DATETIME NULL,
  `convite_enviado` TINYBLOB NULL,
  `respondida` TINYBLOB NULL,
  `id_turma_aluno` BIGINT(20) NULL,
  `id_questionario` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliacao_turma_x_aluno1_idx` (`id_turma_aluno` ASC),
  INDEX `fk_avaliacao_questionario1_idx` (`id_questionario` ASC),
  CONSTRAINT `fk_avaliacao_turma_x_aluno1`
    FOREIGN KEY (`id_turma_aluno`)
    REFERENCES `avaliacaoinfnet`.`turma_x_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_questionario1`
    FOREIGN KEY (`id_questionario`)
    REFERENCES `avaliacaoinfnet`.`questionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`categoria` (
  `id` BIGINT(20) NOT NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`questao` (
  `id` BIGINT(20) NOT NULL,
  `enunciado` VARCHAR(45) NULL,
  `id_categoria` BIGINT(20) NULL,
  `id_questionario` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modelo_questao_categoria1_idx` (`id_categoria` ASC),
  INDEX `fk_modelo_questao_questionario1_idx` (`id_questionario` ASC),
  CONSTRAINT `fk_modelo_questao_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `avaliacaoinfnet`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelo_questao_questionario1`
    FOREIGN KEY (`id_questionario`)
    REFERENCES `avaliacaoinfnet`.`questionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacaoinfnet`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacaoinfnet`.`resposta` (
  `id` BIGINT(20) NOT NULL,
  `resposta` TINYBLOB NULL,
  `id_avaliacao` BIGINT(20) NULL,
  `id_questao` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questao_avaliacao1_idx` (`id_avaliacao` ASC),
  INDEX `fk_questao_modelo_questao1_idx` (`id_questao` ASC),
  CONSTRAINT `fk_questao_avaliacao1`
    FOREIGN KEY (`id_avaliacao`)
    REFERENCES `avaliacaoinfnet`.`avaliacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questao_modelo_questao1`
    FOREIGN KEY (`id_questao`)
    REFERENCES `avaliacaoinfnet`.`questao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
